services:
  nginx:
    build: ./frontend
    container_name: react
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d 
    environment:
      - NODE_ENV=production
    networks:
      - public_network
    depends_on:
      - springboot
  springboot:
    build: ./backend
    container_name: springboot
    ports:
      - 8080:8080
    networks:
      - public_network
networks:
  public_network:
    name: public_network